language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then goveralls -coverprofile=coverage.out -service travis-ci -repotoken ${COVERALLS_TOKEN}; fi'

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"

deploy:
  provider: script
  skip-cleanup: true
  script: ghr --username kaishuu0123 --token $GITHUB_TOKEN --replace --debug $(git tag -l --contains HEAD) dist/
  on:
    tags: true
